minimum_pre_commit_version: "2.9.0"
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
        language: python
        language_version: "python3"
        additional_dependencies: [click==7.1.2, black==21.12b0]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: [
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
        ]
  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-toml"
      - id: "check-yaml"
      - id: "check-merge-conflict"
  - repo: "https://gitlab.com/bmares/check-json5"
    rev: "v1.0.0"
    hooks:
      - id: "check-json5"
  - repo: "https://github.com/teemtee/tmt.git"
    rev: "1.33.0"
    hooks:
      - id: "tmt-tests-lint"
        verbose: false

  - repo: https://github.com/packit/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: check-rebase
        args:
          - https://github.com/oamg/convert2rhel.git
        stages: [manual, push]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        stages: [manual, push]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
