minimum_pre_commit_version: "2.9.0"
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
        language: python
        language_version: "python3"
        additional_dependencies: [click==7.1.2, black==21.12b0]
        args:
          - "--target-version=py27"
          - "--target-version=py36"
          - "--target-version=py37"
          - "--target-version=py38"
          - "--target-version=py39"
          - "--target-version=py310"

  - repo: "https://github.com/timothycrosley/isort"
    rev: 5.11.4
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-toml"
      - id: "check-yaml"
      - id: "check-merge-conflict"
  - repo: "https://gitlab.com/bmares/check-json5"
    rev: "v1.0.0"
    hooks:
      - id: "check-json5"
  - repo: "https://github.com/teemtee/tmt.git"
    rev: "1.20.0"
    hooks:
      - id: "tmt-tests-lint"
        verbose: false
