name: Tests Label Commenter

on:
  pull_request_target:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: always() && github.repository == 'oamg/convert2rhel'
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          sparse-checkout: |
            .github/label-commenter-config.yml
          sparse-checkout-cone-mode: false
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1.10.0
        env:
          RUNNER_DEBUG: 1
        with:
          github_token: ${{ secrets.LABEL_COMMENTER }}
