name: pylint

env:
  interpreted_pylint: |
    function fail_on_fatal_or_error_only() {
      # We care about fatal (1) and error (2) messages only.
      # The exit code is a sum of numbers corresponding to the message severity level.
      # E.g. if there are both error (2) and warning (4) messages, the exit code is 6.
      local exit_code=0
      pylint --rcfile=.pylintrc convert2rhel/ || exit_code=$?
      if ! [ $((exit_code & 3)) -eq 0 ]; then
        return $exit_code;
      fi;
      return 0;
    }
    fail_on_fatal_or_error_only

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:        
  pylint_check_2_6:
    runs-on: ubuntu-latest
    container: centos:centos6

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1


    - name: Install Requirements
      run: |
        yum install -y python-six pexpect
        curl https://bootstrap.pypa.io/2.6/get-pip.py -o get-pip.py
        python get-pip.py
        pip install pylint==1.1.0
        pip install astroid==1.2

    - name: Run Pylint Checks
      run: ${{ env.interpreted_pylint }}

  pylint_check_2_7:
    runs-on: ubuntu-latest
    container: centos:centos7

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum --enablerepo=extras install -y epel-release  # to get pylint
        yum install -y python-six pylint pexpect

    - name: Run Pylint Checks
      run: ${{ env.interpreted_pylint }}

  pylint_check_3:
    runs-on: ubuntu-latest
    container: centos:centos8

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum --enablerepo=extras install -y epel-release  # to get pylint
        yum install -y pylint python3-pexpect
        
    - name: Run Pylint Checks
      run: ${{ env.interpreted_pylint }}
