name: reuse-tests-tier0@TF

on:
  workflow_call:
    secrets:
      DEBUG:
        required: true
      RHSM_KEY:
        required: true
      RHSM_ORG:
        required: true
      RHSM_PASSWORD:
        required: true
      RHSM_POOL:
        required: true
      RHSM_SERVER_URL:
        required: true
      RHSM_SINGLE_SUB_PASSWORD:
        required: true
      RHSM_SINGLE_SUB_POOL:
        required: true
      RHSM_SINGLE_SUB_USERNAME:
        required: true
      RHSM_USERNAME:
        required: true
      SATELLITE_KEY:
        required: true
      SATELLITE_KEY_EUS:
        required: true
      SATELLITE_ORG:
        required: true
      TF_ENDPOINT:
        required: true
      TF_API_KEY:
        required: true
    inputs:
      copr_artifacts:
        required: true
        type: string
      tmt_plan_regex:
        type: string
        required: false
        default: "^(?!.*tier0)"
      environment_settings:
        type: string
        required: false
        default: '{"provisioning": {"post_install_script": "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"}}'
      arch:
        type: string
        required: false
        default: "x86_64"
      pull_request_status_name:
        type: string
        required: false
        default: "tier0"
      copr:
        type: string
        required: false
        default: "epel-8-x86_64"
      tmt_context:
        type: string
        required: false
        default: "distro=centos-8"
      distros:
        type: string
        required: true
      variables:
        type: string
        required: false
        default: ""
      update_pull_request_status:
        type: string
        required: false
        default: "true"

jobs:
  convert_distro_to_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.convert_to_matrix.outputs.matrix }}
    steps:
      - id: convert_to_matrix
        run: |
          echo "::set-output name=matrix::$input"
        env:
          input: ${{ inputs.distros }}

  reusable_workflow_job:
    # This job only runs for '/rerun' pull request comments by owner, member, or collaborator of the repo/organization.
    name: Schedule regression tests on Testing Farm
    needs: [convert_distro_to_matrix]
    strategy:
      fail-fast: false
      matrix:
        distro: ${{fromJson(needs.convert_distro_to_matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Schedule regression testing for ${{ inputs.pull_request_status_name }}
        uses: sclorg/testing-farm-as-github-action@v1.2.11
        with:
          # required
          api_url: ${{ secrets.TF_ENDPOINT }}
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: "https://github.com/oamg/convert2rhel"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optional
          tf_scope: "private"
          create_issue_comment: "true"
          update_pull_request_status: ${{ inputs.update_pull_request_status }}
          tmt_plan_regex: ${{ inputs.tmt_plan_regex }}
          compose: ${{ matrix.distro }}
          arch: ${{ inputs.arch }}
          copr: ${{ inputs.copr }}
          copr_artifacts: ${{ inputs.copr_artifacts }}
          debug: ${{ secrets.DEBUG }}
          tmt_context: "distro=${{ matrix.distro }}"
          pull_request_status_name: ${{ inputs.pull_request_status_name }}
          environment_settings: ${{ inputs.environment_settings }}
          variables: "DEBUG=${{ secrets.DEBUG }};\
            RHSM_KEY=${{ secrets.RHSM_KEY }};\
            RHSM_ORG=${{ secrets.RHSM_ORG }};\
            RHSM_PASSWORD=${{ secrets.RHSM_PASSWORD }};\
            RHSM_POOL=${{ secrets.RHSM_POOL }};\
            RHSM_SERVER_URL=${{ secrets.RHSM_SERVER_URL }};\
            RHSM_SINGLE_SUB_PASSWORD=${{ secrets.RHSM_SINGLE_SUB_PASSWORD }};\
            RHSM_SINGLE_SUB_POOL=${{ secrets.RHSM_SINGLE_SUB_PASSWORD }};\
            RHSM_SINGLE_SUB_USERNAME=${{ secrets.RHSM_SINGLE_SUB_PASSWORD }};\
            RHSM_USERNAME=${{ secrets.RHSM_USERNAME }};\
            SATELLITE_KEY=${{ secrets.SATELLITE_KEY }};\
            SATELLITE_KEY_EUS=${{ secrets.SATELLITE_KEY_EUS }};\
            SATELLITE_ORG=${{ secrets.SATELLITE_ORG }};\
            ${{ inputs.variables }}"
